# Generated by Django 5.0 on 2024-02-25 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kapsula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('PREMIUM', 'premium'), ('RELAX', 'relax'), ('BASIC', 'basic')], default='PREMIUM', max_length=16)),
                ('poziom', models.CharField(choices=[('GORNY', 'gorny'), ('DOLNY', 'dolny')], default='DOLNY', max_length=16)),
                ('plec', models.CharField(choices=[('FEMALE', 'female'), ('MALE', 'male'), ('FAMILY', 'family')], default='FEMALE', max_length=16))
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapsula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kapsuly.kapsula')),
            ],
        ),
        migrations.AlterModelOptions(
            name='kapsula',
            options={'verbose_name_plural': 'Kapsuly'},
        ),
        migrations.AlterModelOptions(
            name='rezerwacja',
            options={'verbose_name_plural': 'Rezerwacje'},
        )
    ]
